from utils.exceptions.exception_handler import custom_exception_handler